# Generated by Django 4.1 on 2023-01-10 03:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_post_liked_by_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='people_followed',
            field=models.ManyToManyField(blank=True, related_name='follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
